version: '3.8'

services:
  vault:
    build: ./vault-config
    container_name: hashicorp-vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev-token
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    networks:
      - vault-network

  webapp:
    build: ./webapp
    container_name: vault-webapp
    ports:
      - "3000:3000"
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=dev-token
    depends_on:
      - vault
    networks:
      - vault-network

networks:
  vault-network:
    driver: bridge
