apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-v2
  labels: { app: demo, version: v2 }
spec:
  replicas: 2
  selector:
    matchLabels: { app: demo, version: v2 }
  template:
    metadata:
      labels: { app: demo, version: v2 }
    spec:
      containers:
        - name: color-app
          image: color-app:latest          # o <tu_usuario>/color-app:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: VERSION
              value: "v2"
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 2
            periodSeconds: 3
